[colors]
[colors.primary]
background = "#141414"
foreground = "#ffffff"

[colors.normal]
black   = "#141414"
red     = "#e71852"
green   = "#60cc57"
yellow  = "#eda912"
blue    = "#0a64f5"
magenta = "#fbfbff"
cyan    = "#ffffff"
white   = "#cdd6f4"

[colors.bright]
black   = "#636363"
red     = "#e71852"
green   = "#60cd57"
yellow  = "#eda912"
blue    = "#0a64f5"
magenta = "#fbfbff"
cyan    = "#ffffff"
white   = "#ffffff"

[colors.cursor]
text   = "#141414"
cursor = "#ffffff"
